name: Build, Run and Finalize Deploy

on:
  push:
    branches:
      - test

jobs:
  deploy-on-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS 
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            sudo docker stop $(sudo docker ps -a -q) || true
            sudo docker rm $(sudo docker ps -a -q) || true
            if [ ! -d ~/BeginnersAppDev/CDA_fil_rouge ]; then
              mkdir -p ~/BeginnersAppDev
              git clone --branch test https://github.com/LegrandThomas/CDA_fil_rouge.git ~/BeginnersAppDev/CDA_fil_rouge
            else
              cd ~/BeginnersAppDev/CDA_fil_rouge
              git pull origin test
            fi

  build-and-run-on-vps:
    runs-on: ubuntu-latest
    needs: deploy-on-vps

    steps:
      - name: Build Docker Containers 
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/BeginnersAppDev/CDA_fil_rouge
            sudo docker-compose down
            sudo docker-compose build --parallel

      - name: Start Docker Containers
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/BeginnersAppDev/CDA_fil_rouge
            sudo docker-compose up -d
